#!/usr/bin/env python
# coding: utf-8
import sys
import sockethandler

def main(argv):
    hostName = argv[0]
    portNumber = int(argv[1])
    user = argv[2]
    robotName = argv[3]

    listening = True
    while listening:
        line = sys.stdin.readline()
        if not line:
            break
        else:
            if(":quit" in line):
                print "goodbye."
                break
            sys.stdout.write("{0}: {1}".format(user,line))
            client = sockethandler.SocketHandler()
            message = "{0}\x00{1}\x00{2}\x00".format(user,robotName,line);
            client.connect(hostName, portNumber)
            client.send(message)
            response = client.receive()
            client.close()
            print "{0}: {1}".format(robotName,response)


if __name__ == "__main__":
    main(sys.argv[1:])
